config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "static#index"

  resources :users, only: [:show] do
    resources :foods
  end

  resources :users, only: [:show] do
    resources :exercises
  end
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  belongs_to :user
  validates :exercise_name, presence: true
  validates :calories_burned, presence: true
end

app/models/exercises.rb
class Exercise < ActiveRecord::Base
  belongs_to :user
  validates :exercise_name, presence: true
  validates :calories_burned, presence: true
end

app/models/food.rb
class Food < ActiveRecord::Base
  belongs_to :user
  validates :food_name, presence: true
  validates :calories, presence: true
end

app/models/foods.rb
class Food < ActiveRecord::Base
  belongs_to :user
  validates :food_name, presence: true
  validates :calories, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :foods
  has_many :exercises
  validates_presence_of :username

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end
  before_action :configure_permitted_parameters, if: :devise_controller?


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :password, :email, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:username, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController

  def new
    @user = current_user
    @exercise = @user.exercises.new
  end

  def create
    @user = current_user
    @exercise = @user.exercises.new(exercise_params)
    if @exercise.save
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def edit
    @user = current_user
    @exercise = @user.exercises.find(params[:id])
    render :edit
  end

  def update
    @user = current_user
    @exercise = @user.exercises.find(params[:id])
    if @exercise.update(exercise_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    @user = current_user
    @exercise = @user.exercises.find(params[:id])
    @exercise.destroy
    redirect_to user_path(@user)
  end

  private
  def exercise_params
    params.require(:exercise).permit(:exercise_name, :calories_burned)
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def new
    @user = current_user
    @food = @user.foods.new
  end

  def create
    @user = current_user
    @food = @user.foods.new(food_params)
    if @food.save
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def edit
    @user = current_user
    @food = @user.foods.find(params[:id])
    render :edit
  end

  def update
    @user = current_user
    @food = @user.foods.find(params[:id])
    if @food.update(food_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    @user = current_user
    @food = @user.foods.find(params[:id])
    @food.destroy
    redirect_to user_path(@user)
  end

  private
  def food_params
    params.require(:food).permit(:food_name, :calories)
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show

    @user = current_user

    if params[:food_sort]
      @foods = @user.foods.order(params[:food_sort] + " " + params[:food_direction])
    else
      @foods = @user.foods.order('food_name')
    end

    if params[:exer_sort]
      @exercises = @user.exercises.order(params[:exer_sort] + " " + params[:exer_direction])
    else
      @exercises = @user.exercises.order('exercise_name')
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def exer_sortable(exer_column, exer_title = nil)
    exer_title ||= exer_column.titleize
    exer_direction = (exer_column == params[:exer_sort] && params[:exer_direction] == "asc") ? "desc" : "asc"
    link_to exer_title, exer_sort: exer_column, exer_direction: exer_direction, food_sort: params[:food_sort], food_direction: params[:food_direction]
  end

  def food_sortable(food_column, food_title = nil)
    food_title ||= food_column.titleize
    food_direction = (food_column == params[:food_sort] && params[:food_direction] == "asc") ? "desc" : "asc"
    link_to food_title, food_sort: food_column, food_direction: food_direction, exer_direction: params[:exer_direction], exer_sort: params[:exer_sort]
  end
end



# exer_direction = (exer_column == params[:exer_sort] && params[:exer_direction] == "asc") ? "desc" : "asc"
#
# if exer_column == params[:exer_sort]
#   if exer_direction == "asc"
#     exer_direction = "desc"
#   else
#     exer_direction = "asc"
#   end
# end

# exer_direction = exer_direction == "asc" ? "desc" : "asc"



# exer_title ||= exer_column.titleize
#
# if exer_title == nil
#   exer_title = exer_column.titleize
# end

app/views/exercises/_form.html.erb
<%= form_for [@user, @exercise] do |f| %>
  <%= f.label :exercise_name %>
  <%= f.text_field :exercise_name %>
  <%= f.label :calories_burned %>
  <%= f.text_field :calories_burned %>
  <%= f.submit %>
<% end %>

app/views/exercises/edit.html.erb
<h1>Edit exercise</h1>

<%= render "form" %>

app/views/exercises/new.html.erb
<h1>Add an Exercises</h1>

<%= render "form" %>

app/views/foods/_form.html.erb
<%= form_for [@user, @food] do |f| %>
  <%= f.label :food_name %>
  <%= f.text_field :food_name %>
  <%= f.label :calories %>
  <%= f.text_field :calories %>
  <%= f.submit %>
<% end %>

app/views/foods/edit.html.erb
<h1>Edit food</h1>

<%= render "form" %>

app/views/foods/new.html.erb
<h1>Add a Foods</h1>

<%= render "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HealthTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path %> |
        <%= link_to "Login", new_user_session_path %>
      <% end %>

    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, id: "flash_#{name}" %>
    <% end %>

    <%= yield %>
  </div>

</body>
</html>

app/views/users/_tables.html.erb
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th><%= exer_sortable "exercise_name" %></th>
      <th><%= exer_sortable "calories_burned" %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @exercises.each do |exercise| %>
    <tr>
      <td><%= exercise.exercise_name %></td>
      <td><%= exercise.calories_burned %></td>
        <td><%= link_to "Edit", edit_user_exercise_path(@user, exercise) %> |
        <%= link_to "Delete", user_exercise_path(@user, exercise), method: "Delete" %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<hr>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th><%= food_sortable "food_name" %></th>
      <th><%= food_sortable "calories" %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @foods.each do |food| %>
    <tr>
      <td><%= food.food_name %></td>
      <td><%= food.calories %></td>
        <td><%= link_to "Edit", edit_user_food_path(@user, food) %> |
        <%= link_to "Delete", user_food_path(@user, food), method: "Delete" %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<h1>Howdy <%= current_user.username %></h1>

<%= form_tag user_path, method: 'get' do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search", name: nil %>
<% end %>

<div id="tables">
  <%= render 'tables' %>
</div>
<hr>
<%= link_to "Add an Exercise", new_user_exercise_path(current_user) %> |
<%= link_to "Add a Food", new_user_food_path(current_user) %>

app/views/users/show.js.erb
$("#tables").html("<%= j render('tables') %>");